apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_USERNAME:  Q1cxMjM=  # Base64 encoded "admin"
  MONGO_PASSWORD: MjFuUlpGUDFmc2JWUVVjMA=== # Base64 encoded "password"